name: solid_theme_work
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mockito: ^5.4.2

flutter:
  uses-material-design: true
